en =
  signIn: "Sign In"
  signin: "sign in"
  signOut: "Sign Out"
  signUp: "Register"
  OR: "OR"
  forgotPassword: "Forgot your password?"
  submit: "submit"
  confirm: "confirm"
  emailAddress: "Email Address"
  emailResetLink: "Email Reset Link"
  dontHaveAnAccount: "Don't have an account?"
  resetYourPassword: "Set your password"
  updateYourPassword: "Update your password"
  password: "Password"
  confirmPassword: "Confirm Password"
  usernameOrEmail: "Username or email"
  email: "Email"
  ifYouAlreadyHaveAnAccount: "If you already have an account"
  signUpWithYourEmailAddress: "Register with your email address"
  username: "Username"
  name: "Name"
  optional: "Optional"
  signupCode: "Registration Code"
  clickAgree: "By clicking Register, you agree to our"
  privacyPolicy: "Privacy Policy"
  terms: "Terms of Use"
  sign: "Sign"
  configure: "Configure"
  with: "with"
  createAccount: "Create an Account"
  and: "and"
  "Match failed":  "Match failed"
  "User not found":  "Invalid username and/or password"
  "Incorrect password": "Invalid username and/or password"

  error:
    minChar: "Passwords are required to be at least 8 characters long."
    maxChar: "Passwords cannot be more than 24 characters long."
    pwOneUppercaseLetter: "Passwords are required to contain 1 upper case letter."
    pwOneLowercaseLetter: "Passwords are required to contain 1 lower case letter."
    pwOneSpecialCharacter: "Passwords are required to contain 1 of these special characters . ! @ # $ % ^ & "
    pwOneDigit: "Password must have at least one digit."
    confirmPasswordNotMatch: "Confirm password does not match"
    usernameRequired: "Username is required."
    emailRequired: "Email is required."
    signupCodeRequired: "Registration code is required."
    signupCodeIncorrect: "Registration code is incorrect."
    signInRequired: "You must be signed in to do that."
    usernameIsEmail: "Username cannot be an email address."
    invalidEmail: "Email is not valid"
    domainNotRegistered: "Please use the email address that is associated with your organization.  Please contact support@riffyn.com if you believe something is amiss or if you would like to obtain a new account. (Please include your phone number if you prefer a call back.)"

T9n.map "en", en
