en =
  signIn: "Sign In"
  signin: "sign in"
  signOut: "Sign Out"
  signUp: "Register"
  OR: "OR"
  forgotPassword: "Forgot your password?"
  submit: "submit"
  confirm: "confirm"
  emailAddress: "Email Address"
  emailResetLink: "Email Reset Link"
  dontHaveAnAccount: "Don't have an account?"
  resetYourPassword: "Set your password"
  updateYourPassword: "Update your password"
  password: "Password"
  confirmPassword: "Confirm Password"
  usernameOrEmail: "Username or email"
  email: "Email"
  ifYouAlreadyHaveAnAccount: "If you already have an account"
  signUpWithYourEmailAddress: "Register with your email address"
  username: "Username"
  name: "Name"
  optional: "Optional"
  signupCode: "Registration Code"
  clickAgree: "By clicking Register, you agree to our"
  privacyPolicy: "Privacy Policy"
  terms: "Terms of Use"
  sign: "Sign"
  configure: "Configure"
  with: "with"
  createAccount: "Create an Account"
  and: "and"
  "Match failed":  "Match failed"
  "User not found":  "User not found"

  error:
    minChar: "7 character minimum password."
    pwOneLetter: "Password requires 1 letter."
    pwOneDigit: "Password must have at least one digit."
    confirmPasswordNotMatch: "Confirm password does not match"
    usernameRequired: "Username is required."
    emailRequired: "Email is required."
    signupCodeRequired: "Registration code is required."
    signupCodeIncorrect: "Registration code is incorrect."
    signInRequired: "You must be signed in to do that."
    usernameIsEmail: "Username cannot be an email address."
    invalidEmail: "Email is not valid"
    domainNotRegistered: "Sorry, it seems that email domain is not registered with Riffyn.  Please use the email address that is associated with your organization.  Please contact support@riffyn.com if you believe something is amiss or if you would like to obtain a new account. (Please include your phone number if you prefer a call back.)"

T9n.map "en", en
